version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 54321
      POSTGRES_DB: autoria_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./dumps:/core/dumps
    command: >
      sh -c "alembic upgrade head && python main.py"

volumes:
  pgdata: