"""init db

Revision ID: 8a837faba69c
Revises: 
Create Date: 2025-05-28 00:28:35.284490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a837faba69c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price_usd', sa.Integer(), nullable=True),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('images_count', sa.Integer(), nullable=True),
    sa.Column('car_number', sa.String(length=50), nullable=True),
    sa.Column('car_vin', sa.String(length=100), nullable=True),
    sa.Column('datetime_found', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
